### ISSUE TITLE
update README.MD

### ISSUE THREAD

**Issue by ltutar** [codedevote/docker-nginx-ssl-proxy-rancher#2] opened 2017-07-05 12:26 UTC
I had to start the container with the option 
```
--link <RANCHER_CONTAINER_NAME>
```
An example is given below:
```
docker run -d -p 80:80 -p 443:443  --link rancher-server -e 'RANCHER_CONTAINER_NAME=rancher-server' -v $EXT_DIR:/etc/nginx/external/ codedevote/nginx-ssl-proxy-rancher
```
Otherwise, I get the following error and I am not able to start the container.
```
[root@server tmp]# docker logs fe3
>> no $DH_SIZE specified using default

codedevote/nginx-ssl-rancher-server
  based on marvambass/nginx-ssl-secure

Nginx reverse proxy with ssl termination 
for running rancher/server over https.

>> setting rancher url to localhost
>> copy /etc/nginx/external/*.conf files to /etc/nginx/conf.d/
>> exec docker CMD
nginx
2017/07/05 12:22:34 [emerg] 1#1: host not found in upstream "rancher-server:8080" in /etc/nginx/conf.d/rancher.conf:5
nginx: [emerg] host not found in upstream "rancher-server:8080" in /etc/nginx/conf.d/rancher.conf:5
```

**Comment by codedevote** [comment] 2017-07-05 12:38
Hmm, that's odd. I never had to use the --link option, the option is also deprecated for some time (see https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/). Are your containers on the same docker network?

**Comment by ltutar** [comment] 2017-07-05 12:45
Both containers use bridge.
```
        "Containers": {
            "2f7c6c7c0e1405332c37cfc38199a01a2eb1e503c0816d60d3a16dcdab30c817": {
                "Name": "elegant_austin",
                "EndpointID": "b0c24e2dc569b11115278dcbd2143bad7a0794f9c56df962472e530a316c1a14",
                "MacAddress": "02:42:ac:11:00:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": ""
            },
            "35da9c336f50f81986696367b575a4150381f12f86851b0e31b8cc434b37c609": {
                "Name": "r-network-services-metadata-1-28461947",
                "EndpointID": "5cb09bad7113216565809a453c7ed2e1c31e180976e22732fc682fc35872d9b6",
                "MacAddress": "02:93:b3:4e:3e:12",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "493dd4aa408322692ef0b0103ab176464e0ab54c32912e0d89a52599c2b54d40": {
                "Name": "rancher-server",
                "EndpointID": "37ceb0958084df131bc8d5e53ac67c6412a5807709dfba9ce7ac91df7865d7d6",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },

```

**Comment by ltutar** [comment] 2017-07-05 12:51
Also according to documentation http://rancher.com/docs/rancher/v1.5/en/installing-rancher/installing-server/basic-ssl-config/ , I read
```
When starting your nginx container, the command must include --link=rancher-server for this exact configuration to work.
```

**Comment by codedevote** [comment] 2017-07-05 15:40
Ok, maybe now I know what's happening. Do you start your rancher server with port forwarding 8080:8080 or don't you forward any ports? If so, then it would explain, why it can be reached when using --link but can't be reached otherwise. Can you confirm this? I will then update the readme accordingly, so the possible configurations are listed. BTW, thx for reporting 😃

**Comment by ltutar** [comment] 2017-07-06 06:26
Hi Florian,

I do use port forwarding when I start Rancher through Ansible.

```
- name: Pull and run the Rancher/server container
  raw: sudo docker run -d --restart always -v /opt/cattle/mysql:/var/lib/mysql --name rancher-server -p 8080:8080 {{ '-e ' + rancher_server_env_vars | join (' -e ') }} {{ rancher_server_image }}
  when: docker_ps.stdout.find("rancher-server") == -1
```

**Comment by codedevote** [comment] 2017-07-06 16:32
I was curious what is happening (so I tried it myself on a fresh ubuntu) and I can indeed confirm, that it doesn't work on docker's default bridge network. I don't know if that's a regression of docker or what's the root cause of this (it was working like that before), but I can tell you that it works as described as soon as you put the rancher and nginx container on another docker network (that you can create by calling *docker network create*. 
Since the --link option is deprecated, I would suggest you use a dedicated docker network in your setup as well (that's what the docker docs also suggest) and I will update the docs here accordingly. 
I'll close this issue, since I think it is resolved. Feel free to open a new one should you encounter further problems.

**Closed as completed by codedevote** 2017-07-06 16:32 UTC
